### ISSUE TITLE
is there a way to use Mo with the beta 1.5 survival patch?

### ISSUE THREAD

**Issue by SadisticLquid** [TanninOne/modorganizer#651] opened 2016-04-11 07:56 UTC
tried the solution 3 http://www.nexusmods.com/fallout4/mods/11479/?

didn't work doesn't load mods

**Comment by Askadar** [comment] 2016-04-12 10:20
It's not MO problem, it's Bethesda disabled mods for survivale testing. You could enable them by using autoexec bat with hlp "mod_name" command (hlp stands for  HotLoadPlugin). For this to work you obviously should either install mods to data directory or launch game as usual through MO. Search nexus for 'survival mods' for complete tutorial.

**Comment by filmcriticbeta** [comment] 2016-04-12 12:42
http://forums.nexusmods.com/index.php?/topic/3998460-mods-are-not-disabled-in-survival-beta-beth-changed-how-plugintxt-works/

https://community.bethesda.net/thread/7706

Nope, they didn't disable mods, instead they changed the format plugins.txt ( most likely to support console users ).  In all likelihood MO will need an update to support the new format.

**Comment by SyntheticInsights** [comment] 2016-04-12 21:59
Does anyone know of a temporary work-around? I wrote a tiny program to change plugins.txt to the new format (with the asterisks) and then set it to read only, but as you suggested ModOrganizer doesn't seem to recognize or support the new format and the game fails to launch.

**Comment by SadisticLquid** [comment] 2016-04-13 10:00
there is a workaround but you will need to edit plugins.txt everytime you launch the game

since mo resets the * edits u make in plugins.txt after you shutdown the game

you will need to add * before every mod for it to work

like this:
*SettlementKeywords.esm
*ArmorKeywords.esm
*CROSS_CosmeticFramework.esm
*SpringCleaning.esm
*Arbitration - Resources.esm

this guy http://www.nexusmods.com/fallout4/mods/11479/  made a script to automate it but it still is quite a hassle

is there someway to stop mo from refreshing that plugins.txt?

**Comment by rdunlap** [comment] 2016-04-13 21:59
Since the issue is with a Beta patch where all mods are supposed to be disabled its much to early to tell if this is just another method Bethesda is using to disable mods during beta or during gameplay that is supposed to be Survival mode *(stated implicitly to be different and NOT compatible with a standard game)  or just possibly could be setting up to make the Mods we love compatible with Consoles. All that to say it would be silly to try to code to a feature or change we cant even define for Tannin yet. :) 

and as far as i can tell you cannot stop the refresh of plugins.txt as its hard coded and integral to the function of ModOrganizer itself. 

Robert

**Comment by filmcriticbeta** [comment] 2016-04-14 05:46
I agree entirely. Its not worth patching until 1.5 goes stable as there may be further changes incoming.  My primary reason my earlier post was to raise awareness.  

In a similar vein I'd like to try to dispel the myth regarding disabling mods for betas.  To date, this has simply not been the case for fallout 4.  Every time such a feature gets added to a beta ( the changes to the launcher, deletion of plugins.txt, etc ) these features have carried over into the stable versions.  There is a clear trend developing here, that these changes are requirements to allow for console modding support, and not an attempt to disable mods for pc gamers.

**Comment by hemoroida** [comment] 2016-04-14 12:30
you can simply edit your plugins.txt in mod organizer folder and backup your plugin list with the disk icon, then everytime the file resets just restore your backup

**Comment by rdunlap** [comment] 2016-04-14 20:09
Yes I was not being obtuse. :P only trying to discuss all the parameters so if its being watched for information we are all on the same page. hemoroida, thats a good solution until things get stable and can be presented for changes to MO2. I am not currently playing an active game but did try that to see. good to keep in my toolbag since i anticipate we will need it in the future.

Robert

**Comment by wmcook32** [comment] 2016-04-22 08:43
The issue I am seeing is this:
the game is not reading the ini files nor is it saving where it is told to, which I leave to the fact that MO2
is still alpha. That said, it is so far proven that mods are now being loaded differently than before. As far as my testing has gone, the games refuses to acknowlege the MO2 plugins.txt file period which might be due to the virtual directory stuff I am having issues with. But yes, at the moment if you want to use mods you must edit the plugins.txt and manually add a * before each esp or esm that is not an official DLC.

**Comment by TanninOne** [comment] 2016-05-10 16:45
Fixed in beta 1

**Closed by TanninOne** 2016-05-10 16:45 UTC
