### ISSUE TITLE
[thanks] Thanks

### ISSUE THREAD

**Issue by ogrotten** [TanninOne/modorganizer#547] opened 2016-02-09 00:49 UTC
Setting up 2a4.

I wanted to say thanks for your work on this program. I've had to use NMM during these last couple of weeks and I must say that i've been NONE too pleased about it. Your work here is FAR superior.

If I weren't broke, I'd donate. In lieu of that for now, I will give you whatever kind of upvote that github allows.

**Comment by rdunlap** [comment] 2016-02-09 01:09
ogrotten you and have bounced a couple issues back and forth. Just a heads up and a test request. I have been beating this one up since he posted it. (might have been the first to download it) all the issues i have been involved with seem to be fixed hands down. I did uncover a new issue. The ini from the profile seems not to be used. I did some tinkering and by copying the ini from the profile i wanted to the vanilla location it works. I have no special setups so was lurking here to see if anyone else had this issue. if you would post back up on it for me i would appreciate it. 

Robert

**Comment by ogrotten** [comment] 2016-02-09 02:39
@rdunlap will chk it out.

**Comment by rdunlap** [comment] 2016-02-09 04:02
I hear ya. When you get a chance. To clarify the only ini used by the game using MO2A4 is the one in my documents/mygames folder. I havent found anything else wrong... the VFS seems HUGELY more stable even with xEdit. just this one issue with the INI's and your finds with the installer. I did go back and test another install instance and reproduced your issues as well. did you try importing your mods from NMM before you ditch the lot? may save some downloading later.

Robert

**Comment by ogrotten** [comment] 2016-02-09 04:31
I'm still locking up on load, so I can't get there from here.

Sorry.

**Comment by rdunlap** [comment] 2016-02-09 04:36
bummer. I had that NMM nightmare in my first attempt at doing the S.T.E.P. for Skyrim. I wound up doing a delete and reload also if memory serves. That's when some kind soul pointed MO out to me and I haven't looked back.

Robert

**Comment by Sir1Twist** [comment] 2016-02-09 07:44
You can move your downloads folder from NMM to somewhere else before you delete it. Then have Mod Organizer point to there for your downloads. That, alone, can save time.

**Comment by ogrotten** [comment] 2016-02-09 22:52
@Sir1Twist thanks. Yeah I copied out the archives to the MO DLs folder.

@rdunlap I think you're right. I found out what my problem was with hanging (homemaker bad load ordering) but I think your'e right about loading the fallout4.ini as stated in #546 .

**Comment by rdunlap** [comment] 2016-02-09 23:52
Thanks for checking. :) It will help others that may hang due to bad INI settings since we tend to ignore the vanilla INI once we get set up with MO. I only noticed it since my other profile is set to small resolution to allow me to work on modding easier.

**Comment by TanninOne** [comment] 2016-05-29 08:46
You're welcome. Closing this as it's not an issue report.

**Closed by TanninOne** 2016-05-29 08:46 UTC
