### ISSUE TITLE
Mod Organizer versions problem - Nexus logging problem

### ISSUE THREAD

**Issue by Kevdrag** [TanninOne/modorganizer#1001] opened 2016-10-30 16:07 UTC
Hi!

First of all, thanks for your awsome work and your dedication, there should be something like this for every f*****g, mod posible, game out there....

Well, now to buissnes. It happens that I have 3 versions of MO

1. The "legacy version" for WinXP, obviously, working with Skyrim in WinXP
2. The 1.3.11 nexus version of 32bits I guess
3. And the 2.0.7 Beta version recently downloaded from here 

The last two, both working in Win7 64bits.

Yesterday, around 4pm (UTC -4:00) I opened the Nexus version of MO, in my Win7 PC and could not login to the nexus neither download any mod through MO. It loged something like this

<details>
  <summary>**Click to expand**</summary>
  11:10:34 [D] attempt login with username kevdrag
11:10:34 [D] login failed: Error downloading http://nmm.nexusmods.com/skyrim/Sessions/?Validate - server replied: Service Temporarily Unavailable
11:10:34 [W] QCoreApplication::postEvent: Unexpected null receiver
11:11:12 [C] request (http://nmm.nexusmods.com/skyrim/Mods/1334/?game_id=110) error: Error downloading http://nmm.nexusmods.com/skyrim/Mods/1334/?game_id=110 - server replied: Service Temporarily Unavailable
11:11:12 [W] request failed: Error downloading http://nmm.nexusmods.com/skyrim/Mods/1334/?game_id=110 - server replied: Service Temporarily Unavailable
11:12:12 [W] Failed to retrieve update information: Error downloading http://nmm.nexusmods.com/skyrim/Mods/1334/?game_id=110 - server replied: Service Temporarily Unavailable
11:12:12 [D] Fallo al recuperar informaci�n de actualizaci�n: Error downloading http://nmm.nexusmods.com/skyrim/Mods/1334/?game_id=110 - server replied: Service Temporarily Unavailable
</details>

However, I could download mods manually...

I've came across some statements that says that in recent days (More exactly from yestarday 29/08) the nexus site and/or the NMM download links wasn't working correctly, and that some other people also had problems trying to login to the nexus and downloading mods through the mod managers. I concluded that it was a nexus problem and not MO's (While looking for solutions I saw this github an downloaded the beta, just to give it a try...).

Also read that it's because of the hype for SSE and the enormus amount of attention the nexus is reciving...

Later that day, between 10pm and 3am I tried again, in my "legacy" version of MO, in my WinXP PC (for no special reason) and I was able to login and download with normality, so I thought the Nexus site problem was solved. 

That wouldn't be much of an issue IF i haven't tried, just now, to use normaly the MO in my Win7 PC again, this time through the Beta version of MO; BUT the logging and downlading problem persist. I closed the program, opened the Nexus version, same. 

The log pasted above, is from the Nexus version, opened a while ago.

Reseting and/or reinstaling both programs does not work
Neither reseting computer

I haven't tried to reset the conection but I think it wouldn't do much, as I logged out and in again, to the nexus through the navigator and I'm able to download manually without problems. Also I've conected yesterday from another computer in home (XP) and could login and download through the "legacy" version.

If anyone could throw some ligth to this mistery it would be much apreciated.

**Comment by TanninOne** [comment] 2016-10-30 16:13
"server replied: Service Temporarily Unavailable" should have given you the clue that it's a server problem.
Besides this is a duplicate of the issue immediately below it.

**Closed by TanninOne** 2016-10-30 16:13 UTC

**Comment by Kevdrag** [comment] 2016-11-01 00:32
No, not really. 

I did stated that I have 3 versions MO, 2 of them in one computer and one in the other, in the same house, in the same conection, with the same mods, the same game, the same user and the same password; and yet, I could only login and download normally through the "legacy version". 

In the meanwhile, nothing else worked. Thats the issue.

If it where a nexus problem only, I wouldn't be able to do anything in any computer, in any version, anywhere in the world... and it's not the case.

**Comment by TanninOne** [comment] 2016-11-01 06:51
Service Temporarily Unavailable *is* the response from the server! The nexus server itself says the service is unavailable so why exactly are you still discussing whether the problem is with the server?

And your assumption that you will get reproducible results from a server that is under heavy load is flawed. You argue "At time x I could login with mo1 and at time y login with mo2 failed so there has to be a bug in mo2" when really it has to do with time x vs time y. Mo1 happened to get through with one or two requests, that doesnt mean that when mo1 asks there is no heavy load on the server
