### ISSUE TITLE
Startup Exception

### ISSUE THREAD

**Issue by gravypod** [TanninOne/modorganizer#401] opened 2015-11-30 00:43 UTC
I get this message box http://i.imgur.com/uuRc4Q0.png
After clicking ok, the application starts fine.

The mod organizer loads all of my mods and starts correctly. I've just taken to ignoring the box.

**Comment by Goofysoccer** [comment] 2015-11-30 02:07
Yep, that's no big deal, just a small bug. Should be fixed soon

**Comment by TanninOne** [comment] 2015-11-30 07:01
There is already a report for ths: issue #366

**Comment by jerry7890** [comment] 2016-01-04 17:35
Fix at #427

**Comment by TanninOne** [comment] 2016-01-04 17:54
duplicate of #366

**Closed by TanninOne** 2016-01-04 17:54 UTC
