### ISSUE TITLE
[v2.0.6] Muti-game (non-portable) install not working

### ISSUE THREAD

**Issue by dt78** [TanninOne/modorganizer#786] opened 2016-06-04 19:03 UTC
When doing a fresh install of MO v2.0.6, selection of  "New instance" instead generates a "Portable" MO configuration. After selecting the game name and path, the %localappdata%\ModOrganizer\ folder is NOT created, and the mods, downloads, profiles, configuration, ... folders and files are written to the MO program folder.

Running Win 10 Pro 64bit
MO was installed to 2nd HD E:\Program Files\ModOrganizer
MO was launched as administrator.

**Comment by EyeWasAPerson** [comment] 2016-06-05 04:25
This issue's about the same as issue #759 actually and I have the same problem. No matter if I'm running the program on the C: drive or any external hard drive, whether I run MO as an administrator or not, if I select the option to create a new instance it will prompt me to create the instance name but then immediately revert to portable mode without creating any folder in %localappdata%\ModOrganizer\ . There's nothing as far as error messages or anything in mo_interface.log, it treats it as if I'm just running a standard portable installation and I know there's no write permission issues on my computer.

That said, I have found a workaround similarly to issue #759 . If I manually create the folder %localappdata%\ModOrganizer\ and create a subfolder named anything, then MO will recognize the instance whether it's an initial startup or clicking the MO button to open the game select dialog. I can do this for multiple instances and everything works perfectly for each instance. Except that local saves and .ini files don't work properly, but that's a different problem entirely that's already been documented.

**Comment by TanninOne** [comment] 2016-06-05 08:10
Duplicate of issue #759

**Closed by TanninOne** 2016-06-05 08:10 UTC
