### ISSUE TITLE
Profile change = crash (MO2b1)

### ISSUE THREAD

**Issue by Fed13** [TanninOne/modorganizer#718] opened 2016-05-15 11:30 UTC
[ModOrganizer.exe.zip](https://github.com/TanninOne/modorganizer/files/264943/ModOrganizer.exe.zip)
Here's a dump file.

I disabled several mods in the left MO panel.
Got a f4se error (I'll try to make a ticket on that one since f4se works fine if not launched through MO).
Switched to another profile.
... something happened...
And now when I try to switch to the first profile (with disabled mods) - I get a crash every time.

**Comment by TanninOne** [comment] 2016-05-15 11:44
Duplicate of #684

**Closed by TanninOne** 2016-05-15 11:44 UTC
