### ISSUE TITLE
beta 2 generate some weird folders in user home and appdata

### ISSUE THREAD

**Issue by TwistedByte** [TanninOne/modorganizer#756] opened 2016-05-27 23:02 UTC
beta 2 generate some weird folders in user home and appdata
and profile ini's still not work

<a href='http://postimg.org/image/641vpor7v/' target='_blank'><img src='http://s33.postimg.org/641vpor7v/Untitled.jpg' border='0' alt="Untitled" /></a>

it generate new random named folders when fallout 4 is launched
maybe something related to ntdll.dll  (  毤Ȁ耀ntdll.dll  was one of subfolders name )
some lines from usvfs ...

02:11:45.252 [I] create config in 1352
02:11:45.252 [I] 0 processes
02:11:45.268 [I] mod_organizer_instance_1 created in process 1352
02:11:45.268 [I] attached to mod_organizer_instance_1 with 1 nodes, size 65536
02:11:45.268 [I] inv_mod_organizer_instance_1 created in process 1352
02:11:45.268 [I] attached to inv_mod_organizer_instance_1 with 1 nodes, size 65536
02:11:48.415 [I] injecting to process 5948 with same bitness
02:11:48.458 [E] exception in usvfs::hooks::CreateDirectoryW: failed to create intermediate directory (The filename, directory name, or volume label syntax is incorrect. [123])
02:11:48.458 [W] 
02:11:48.614 [E] exception in usvfs::hooks::CreateDirectoryW: failed to create intermediate directory (The filename, directory name, or volume label syntax is incorrect. [123])
02:11:48.614 [W] 
02:11:48.675 <4872:2224> [W] GetCurrentDirectoryA called
02:11:51.174 [E] exception in usvfs::hooks::CreateDirectoryW: failed to create intermediate directory (The filename, directory name, or volume label syntax is incorrect. [123])
02:11:51.174 [W] 
02:12:02.813 [E] exception in usvfs::hooks::CreateDirectoryW: failed to create intermediate directory (The filename, directory name, or volume label syntax is incorrect. [123])
02:12:02.813 [W] 
02:12:03.370 <4872:2224> [W] windows exception c0000005 from C:\Windows\SYSTEM32\MSVCP120.dll

**Comment by TanninOne** [comment] 2016-05-28 08:22
This is a duplicate of issue #753.
I added your post there as the log is very useful. Thanks.

**Closed by TanninOne** 2016-05-28 08:22 UTC
Labels: duplicate
