### ISSUE TITLE
[All Versions] Nothing starts

### ISSUE THREAD

**Issue by ZeroMaki** [TanninOne/modorganizer#710] opened 2016-05-13 03:53 UTC
I'm uncertain of what the issue could be but if I try to launch anything through Mod Organizer be it Alpha2 which worked for me before I uninstalled fallout or the new Beta1, I can launch just fine through steam or script extender but if I try to launch through Mod Organizer it gives me the "locked while X.exe running" and then it disappears and nothing ever started.

**Comment by KeltecRFB** [comment] 2016-05-13 11:40
Related to #700?

**Comment by TanninOne** [comment] 2016-05-13 16:18
There are plenty of reports about problems running applications. You provide no information that could help narrowing it down so I'll assume it's a duplicate of some other issue.

**Closed by TanninOne** 2016-05-13 16:18 UTC
Labels: invalid

**Comment by ZeroMaki** [comment] 2016-05-14 01:38
There are plenty reports, however people say to disable AV that wouldn't change a thing since my AV don't touch my sandbox envireonments it can't see them so the other issues people have had doesn't seem to be the same also others say that it hangs where mine simply opens then closes again it doesn't hang.

**Comment by ZeroMaki** [comment] 2016-05-14 01:56
04:54:27 [W] failed to assign to job object: 50

This is the error I receive with alpha2 that one at least launches the game but doesn't use the mods.
