### ISSUE TITLE
Mod Organizer 2(Alpha 2)

### ISSUE THREAD

**Issue by ScalierNebula** [TanninOne/modorganizer#429] opened 2015-12-10 01:31 UTC
When launching MO I receive this message. 

 failed to initialize plugin C:/Mod Tools/Mod Organizer 2 For Fallout 4/plugins/pyCfg.py: An unexpected C++ exception was thrown in python code

And when I attempt to launch Fallout 4, the game doesn't launch, MO locks for a few seconds and unlocks and nothing happens. I've tried multiple things to try and fix this like fresh install of Fallout 4, and MO2 without any mods installed and it doesn't launch.

**Comment by unobtainer** [comment] 2015-12-10 01:36
pycfg error is a known issue, and is not fatal. 

Which version of Windows are you on? Win7x64 is not currently working.

**Comment by TanninOne** [comment] 2015-12-10 07:30
Duplicate of known issues. Also please never report multiple problems in one report.

**Closed by TanninOne** 2015-12-10 07:30 UTC
Labels: duplicate
