### ISSUE TITLE
Restore Backup does not restore backup

### ISSUE THREAD

**Issue by rdunlap** [TanninOne/modorganizer#721] opened 2016-05-16 01:34 UTC
I made a backup of the esp list to do some testing and unselected all active mods. did my testing and clicked restore button. It does not restore. Checking the actual backup file shows it was made properly, its just not restoring. No error message.

Robert

**Comment by kstarler** [comment] 2016-05-16 04:10
Same as #699

**Comment by TanninOne** [comment] 2016-05-16 09:36
duplicate of #699

**Closed by TanninOne** 2016-05-16 09:36 UTC

**Comment by rdunlap** [comment] 2016-05-16 14:35
Sorry. I was cross eyed tired last night. I will add mine to the original tonight when I get home.

Robert

Sent from my iPhone

On May 16, 2016, at 5:36 AM, TanninOne <notifications@github.com<mailto:notifications@github.com>> wrote:


duplicate of #699<https://github.com/TanninOne/modorganizer/issues/699>

-
