### ISSUE TITLE
MO2B2 Not using Ini files from profiles

### ISSUE THREAD

**Issue by rdunlap** [TanninOne/modorganizer#752] opened 2016-05-27 16:22 UTC
The profile INI files are still not being used. I have tried both a portable install and a standard installation to assure the behavior is consistent. I deleted the ones in the my games/Fallout4 folder to test and see if it was a problem with permissions and the game just recreates them. Lastly I disabled my AV product and tried it. In all cases the profile INI files are not being used.

Robert

**Comment by WhiteZeroX** [comment] 2016-05-27 17:15
Might be related, but my mod ESPs are still not loading in B2 either, from my issue #697

**Comment by rdunlap** [comment] 2016-05-27 17:25
Strange. My esp's are loading fine. its just the silly ini files that are refusing. I game in 5670X1080 but work on my mods *(testing and such) in 1920X1080 so I can move to the desktop for notes and such easier than full screen allows, plus Screen shots in superwide mode look HORRIBLE on the Nexus. I miss my easy switch. 

Robert

**Comment by WhiteZeroX** [comment] 2016-05-27 17:44
Nevermind, I must have had something broken from a previous profile. I deleted and recreated my profile from scratch and they work now. Dunno if my inis are working properly though. Wondering what a good way to test that is.

**Comment by rdunlap** [comment] 2016-05-27 17:46
Change the resolution in one of them is the easiest way.

**Comment by WhiteZeroX** [comment] 2016-05-27 17:48
@rdunlap gotcha, that seems to be the same case here too. At least I got my ESPs working again.  :)

**Comment by rdunlap** [comment] 2016-05-27 17:55
Me either, but if memory serves it does not actually create the ini files. It just pointed to the ones in the profile via the VFS at runtime. that being the case its just something not done in the VFS i suspect. I had hoped it would make it into beta 2.

Robert

**Comment by WhiteZeroX** [comment] 2016-05-27 17:56
@rdunlap right, it's suppose to link them via VFS. But the VFS logs don't show any .inis being used. While I can see every other ESP and loose file in there.

**Comment by rdunlap** [comment] 2016-05-27 17:58
OH! I misunderstood you. :P then my revised answer is Same here.

**Comment by TanninOne** [comment] 2016-05-27 18:48
duplicate of #681 
why do you create a duplicate of your own report???

**Closed by TanninOne** 2016-05-27 18:48 UTC
Labels: duplicate
