### ISSUE TITLE
2.0.3a crash on start.

### ISSUE THREAD

**Issue by ogrotten** [TanninOne/modorganizer#490] opened 2016-01-13 10:09 UTC
Based on advice from a separate issue, I went with a fresh unzip, as opposed to the overwrite unzip I'd done earlier.

I had chosen "single install". MO Crashed after that prompt. Here's the dump.
[ModOrganizer.exe.dmp.zip](https://github.com/TanninOne/modorganizer/files/88656/ModOrganizer.exe.dmp.zip)

I deleted and re-un-zipped the dir and started it again. This time I answered "multiple install". crash again, I don't ahve a dump.

I took the ini from 2.0.2a and overwrote the ini in the multi-install dir.After starting, MO did NOT crash as it had before, but instead gave me an error message that it couldn't find the directory for the profile that i had been using in 2.0.2a and the hybrid.

I then deleted the directory and re-un-zipped again. This time, straight to crash without a prompt for what type of install I want to do.

I deleted the directory buried in the windows profile, started it again, it crashed without prompting me. I dug around in the registry and deleted HKEY_CLASSES_ROOT\...\Tannin.

Upon restart, I was prompted for type of install. I chose Portable and it crashed. I copied over the old .ini and the old profiles directory and now it ran without problem . . . except, of course, the mods list was empty.

I again copied /profiles (overwriting), along with /mods and /downloads. It ran with everything the way i had it in v2.0.2a install, and the v2.0.2a install with 2.0.3 unzipped over it. The exception being that the game now bombs on start... but that's a different problem altogether.

I could probably recreate any of the above conditions on purpose if you have questions or want me to try something.

**Comment by noctred** [comment] 2016-01-13 16:44
Check the gamePath line in your ModOrganizer.ini.

If it's pointing to a New Vegas install or any location other than your Fallout 4 install, change it, make the file read-only, start MO, exit MO, remove the read-only flag, and start MO again.

That's what fixed the crashes for me.

**Comment by ogrotten** [comment] 2016-01-13 17:24
I didn't even look at the ini, I just stomped it outright as I've seen a couple of threads here talk about it doing something unexpected and that overwriting it with the old one fixes it.

**Comment by TanninOne** [comment] 2016-01-13 19:05
duplicate of issue #488

**Closed** 2016-01-13 19:06 UTC
Labels: duplicate
