### ISSUE TITLE
Crash Re-running xEdit in same MO2B3 session

### ISSUE THREAD

**Issue by rdunlap** [TanninOne/modorganizer#815] opened 2016-06-19 17:26 UTC
This was mentioned in another thread i know but i cannot find it so i will outline it here so i can show what Beta 3 FIXED as well as what is not yet fixed.

open MO2B3 run CK and open a plugin and save it. It now properly saves into Overwrite as expected with capitalization fixed properly. Close CK. Re-open CK and any plugin and save Plugin. everything works as expected. This is FIXED in beta 3. In Beta 2 MO2 would crash when you tried to open CK a second time in the same session.

Do the above steps using xEdit instead and when you try to run xEdit the second time MO2B3 crashes. This is The same behavior demonstrated in Beta 2 and before. The fix implemented in CK DID address the name Capitalization issue in both programs, but xEdit is still not happy with something.
Attached is the Crash dump generated. One more note. If you run xEdit and save a plugin and close it and then run Anything it seems it will cause MO2B3 to crash. The dump is from running xEdit first and then trying to run CK.

[ModOrganizer.exe.dmp.zip](https://github.com/TanninOne/modorganizer/files/322401/ModOrganizer.exe.dmp.zip)

Robert

**Comment by darkconsole** [comment] 2016-06-20 00:24
i had mentioned this in the creationkit thread yeah. looking forward to testing that now.

**Comment by darkconsole** [comment] 2016-06-20 00:37
yeah. still does it.
[ModOrganizer.exe.dmp.zip](https://github.com/TanninOne/modorganizer/files/322565/ModOrganizer.exe.dmp.zip)

**Comment by Bigtonytomato** [comment] 2016-06-21 01:46
I opened and closed it ran it a bunch of times in my MO2 and it didn't cause any issues at all. It wouldnt run at all in my last Mo build

**Comment by TanninOne** [comment] 2016-06-21 06:17
Duplicate of #791

**Closed** 2016-06-21 06:17 UTC
Labels: duplicate
