### ISSUE TITLE
MO crashes when trying to merge a mod with an update.

### ISSUE THREAD

**Issue by Wadu436** [TanninOne/modorganizer#478] opened 2016-01-11 16:01 UTC
I tried to update Vivid Landscapes from v1.9 to v2.0 and merged them, but MO crashed and didn't merge the 2 files, but did update the version number to 2.0

Dump: http://puu.sh/mrPbU/2335d59b4f.dmp

**Comment by TanninOne** [comment] 2016-01-12 16:57
Duplicate of issue #480 (yes, this one was first, but the other one contains more info)

**Closed by TanninOne** 2016-01-12 16:57 UTC
Labels: duplicate
