### ISSUE TITLE
Weird folders in user's Documents after using MO2.0.6

### ISSUE THREAD

**Issue by Will40** [TanninOne/modorganizer#784] opened 2016-06-04 14:11 UTC
Hi,

After I started using MO2 I get some strange folders being created in my Documents folder:

![weirdiness](https://cloud.githubusercontent.com/assets/19748591/15799968/bb0e120c-2a65-11e6-8dfe-5b558aa77cb7.png)

I get those after playing Fallout 4 using MO 2, file system checks come up clean. I cannot be completely certain it's MO2 fault, but it started right after installing it. Also some folders have names in them like pppl.dll, which is dll from one of the mods I'm using.

Did anyone have anything similar?

I can provide any other info if needed.

**Comment by TanninOne** [comment] 2016-06-04 16:27
duplicate of #753

**Closed by TanninOne** 2016-06-04 16:27 UTC
Labels: duplicate
