### ISSUE TITLE
Mod Organizer 2 - Vanilla Fallout 4 Doesn't Start

### ISSUE THREAD

**Issue by Goofysoccer** [TanninOne/modorganizer#399] opened 2015-11-29 22:25 UTC
I am on the alpha 2 version of MO2 and Fallout 4 will not start on a completely vanilla install. When I press "run" on either Fallout 4 or Fallout Launcher, it comes up with the "MO is locked while the executable is running" message for about 7 seconds. After those 7 seconds the message disappears and it goes back to the MO screen. Fallout 4 never starts through MO. 

I ran the program as admin from Program Files, Program Files x86, and C:/ and this happened every time. 

LOG: http://pastebin.com/ExZxfiWG
DMP File: http://www.megafileupload.com/mmaJ/usvfs_x64.dll_1448835969.dmp

**Comment by fireundubh** [comment] 2015-11-30 10:58
Same issue with or without mods.

FO4 Runtime: 1.1.30

Tried F4SE, Fallout 4, and Fallout 4 Launcher.

Crashes F4SE with error:

> Unhandled exception at 0x000007FEF213152D (usvfs_x64.dll) in f4se_loader.exe: 0xC0000005: Access violation writing location 0x0000000040001000.

**Comment by TanninOne** [comment] 2015-11-30 20:00
What windows version is that?

**Comment by DeathProxie** [comment] 2015-11-30 20:04
Can't say for sure since I'm not that person( =P ) but I have pretty much the same exact error on Windows 7.

**Comment by fireundubh** [comment] 2015-11-30 20:23
Windows 7 x64 as well.

**Comment by gerbilOFdoom** [comment] 2015-12-01 19:57
Possible solution:

Copy your functional and mod-enabled ini files into ModOrganizer2\profiles\<activeProfile>

**Comment by Goofysoccer** [comment] 2015-12-01 21:37
@gerbilOFdoom I tried copying the inis and also adding/changing those lines in the ini to no avail. Fallout 4 still won't start through Mod Organizer. I also tried deselecting read-only and that also didn't work.

**Comment by fireundubh** [comment] 2015-12-01 21:59
The exception—"thread tried to read from or write to a virtual address for which it does not have the appropriate access"—indicates the problem is not user error. It is likely an issue with however MO addresses virtual memory, and something Tannin will have to investigate and fix.

**Comment by karoupa** [comment] 2015-12-04 03:50
I have the same issue. I just switched over from the bare-bones Mod Manager. Was very excited when I found out MO was now supporting F4.

I'm running windows 7x64. 
Mod Organizer is in D:\Games\ModOrganizer2 (so no Program Files permission issues). 
Steam is also installed to D:\Games\...
Exact same symptoms as OP.

The only thing of note is that when I originally copied it over, there was a little lock icon on the folder. I fixed it by fixing the security permissions to match that of MO1 (which I still have in case I feel the need to go back to skyrim at some point).

**Comment by unobtainer** [comment] 2015-12-05 13:16
The access violation (0xC0000005) crash on launching FO4 seems to be common (or universal) w/the current alpha on Win7x64.

**Comment by AwfulArchdemon** [comment] 2015-12-30 15:06
Same here. It runs the game (in windowed mode...), and about 4 seconds after I see the Press Any Button To Start message in the game, the game turns off entirely, and MO2 unlocks, as if I had done nothing at all. It won't even try to run the launcher.

Win 7 64-bit.

**Comment by dpcarr3** [comment] 2016-01-07 00:03
I had the same issue, had to disable my antivirus in order to launch my game via Mod Organizer 2. I have AVG Ultimate

**Comment by abbyshire** [comment] 2016-01-13 23:10
I'm on Win 7 64-bit as well and MO2 also doesn't open/run the FO4 or FO4 launcher EXEs.

**Comment by CarlCorey** [comment] 2016-01-28 05:51
Everyone seems to be on Win 7. Just to let you know that on Windows 8.1 64 bit I have the same issue as the OP except that the "MO is locked ..." dialog doesn't go away until I dismiss it. Totally vanilla FO4 install, running MO2 from Steam\SteamApps\common\Fallout 4\ModOrganizer2. No difference whether I run as admin or not.

**Comment by karoupa** [comment] 2016-01-28 12:30
I meant to mention this a while ago but I kept forgetting.
I'm on Win7x64 and I was also having the same issues as specified above. I then installed Alpha 3 (even though its for testers only) and I am able to run F4 with it just fine. Not sure if I'm an anomaly.

**Comment by TanninOne** [comment] 2016-02-08 19:58
Can anyone else confirm the Win7 problems are solved with alpha 3 (and now alpha 4)?

**Comment by DeathProxie** [comment] 2016-02-09 01:02
My issue with the game not starting is now fixed. I had no luck with Alpha 3 but Alpha 4 appears to be working fine thus far, I only briefly tested though. Thanks!

**Comment by TanninOne** [comment] 2016-02-10 19:26
Thanks. I'll close this for now.

**Closed by TanninOne** 2016-02-10 19:26 UTC

**Comment by abbyshire** [comment] 2016-02-26 00:40
Darn it, using Alpha 4 didn't work for me.

**Comment by dunlopg54** [comment] 2016-03-01 18:29
Im on windows 10 and so far everything works fine exept when it comes to launching fallout 4, it just wont launch.

**Comment by OneSubtractOne** [comment] 2016-04-28 11:55
Logged in just to say I'm on Windows 10, using Alpha 4. Had the exact same issue with NOTHING being able to run. Including Loot etc. I also use AVG Ultimate as someone further up said, and disabling that made everything work again.
Try Disabling your Antivirus and then hitting run. It worked to fix the issue for me.

**Comment by Ale91** [comment] 2016-05-23 15:27
So is there anything else to do apart from disabling the antivirus each time you start the game?

As for other people, the executable are running if I look at the computer's processes in the task manager, but they don't show up anywhere. 

I am using the beta on windows 10, and yes disabling avg lets me start the game (although not the launcher), but it isn't very practical
