### ISSUE TITLE
Alpha 3 crashes on startup

### ISSUE THREAD

**Issue by DarkenRahhl** [TanninOne/modorganizer#488] opened 2016-01-13 01:13 UTC
Any ideas how I can bypass this?

Ty

Got windows 10 64 bit

**Comment by Nephatrine** [comment] 2016-01-13 18:09
I had the same issue, but all I did to fix it was to use the modorganizer.ini from my previous alpha2 install. It seems like alpha3 didn't even generate an ini file (I selected the portable install so it should be right there alongside the modorganizer.exe - no idea where the "regular" install puts it).

**Comment by TanninOne** [comment] 2016-01-13 19:06
Duplicate of issue #486

**Closed by TanninOne** 2016-01-13 19:06 UTC
Labels: duplicate
