### ISSUE TITLE
Failed to Identify EXE Type

### ISSUE THREAD

**Issue by RestedWicked** [TanninOne/modorganizer#853] opened 2016-07-02 00:56 UTC
regarding this error when trying to run f4se:
1. since I can run it as long as I start MO2 through an elevated command prompt, but not through the shortcut set to run as admin, maybe MO (or windows) is resetting the credentials since f4se is 1 level above the 'Data' folder and therefore outside the vfs structure (I don't really know if it is outside, don't know what folders exactly it links, ain't gonna pretend I do)?
2. "becomes active only during the initialization phase of each process so it may not be active at the time dependent dlls are loaded". this caught my attention but if it this was the case it wouldn't make sense for it to work when starting MO through an elevated prompt right? do I make any sense? english is not my mother tongue, feel free to correct me.

**Comment by TanninOne** [comment] 2016-07-02 15:04
duplicate of issue #758

**Closed by TanninOne** 2016-07-02 15:04 UTC
