### ISSUE TITLE
Still having the high unicode disk corruption occuring with recommended uvfs file installed.

### ISSUE THREAD

**Issue by Jeoshua** [TanninOne/modorganizer#810] opened 2016-06-17 06:33 UTC
https://s26.postimg.org/z0395k495/Done_with_it.jpg

The person I am reporting this about is very knowledgeable, and very upset. It only occurs while using xEdit. Also, this is not a repeat of the previous errors because this is occurring with the supposed fix that was in #753 

She feels it must be related to 64-bit somehow... I'm not sure if she's right but it might be a clue.

**Comment by TanninOne** [comment] 2016-06-17 14:46
This is still a duplicate of issue #753 . And if this indeed happens with the mentioned patch, please add a usvfs_<date>.log from a xedit-run there.

**Closed by TanninOne** 2016-06-17 14:46 UTC
