### ISSUE TITLE
Fallout 4 plugins.txt layout breaking change

### ISSUE THREAD

**Issue by ubuntufreakdragon** [TanninOne/modorganizer#666] opened 2016-05-01 23:15 UTC
the current Fallout 4 version has the way how the plugins.txt work changed:
Bethesda Files aren't mentioned in it anymore e.g. Fallout4.esm
plugins have to start with a * before the filename.

**Comment by Akzyra** [comment] 2016-05-01 23:45
Already reported: #663 
You can find several fixes as well so you can play until MO2 gets updated.
And he is working on it: #660

**Comment by TanninOne** [comment] 2016-05-09 19:09
duplicate of #663

**Closed by TanninOne** 2016-05-09 19:09 UTC
Labels: duplicate
