### ISSUE TITLE
Empty Folders in Chinese in Documents/My Games 

### ISSUE THREAD

**Issue by valenrynn** [TanninOne/modorganizer#799] opened 2016-06-11 00:47 UTC
Yeah, so this is kind of weird.  I'm a pretty experienced MO user as I've used it for Skyrim for two years with very few issues, so I wanted to use it for Fallout 4 too.  I know how it works but this has me confused.  

I'm using MO2 for Fallout 4 and every time I launch the game, it creates empty folders in "Documents/My Games" but the writing is in Chinese.  Sometimes there are folders within folders, but they're always empty and always in Chinese.  I had about 10 of them in there, once in awhile there is one or two in the Fallout 4 folder itself.  It's directly related to MO as I've tested it several times and checked the time stamps.  One is created every time I start up the game with MO.  Not sure what could be causing it... is it a bug?  I checked these forums and I don't see anyone else having this issue, unless I missed it. 

Also, I know it's Beta and I don't expect things to work perfectly but after three or four times logging into the game via the F4SE launcher, it just refuses to load through MO and I have to restart my computer for it to work again.  Launching Fallout 4 without the script extender works fine.

**Comment by rdunlap** [comment] 2016-06-11 04:41
read this thread. It likely has your solution. https://github.com/TanninOne/modorganizer/issues/753

Robert

**Comment by TanninOne** [comment] 2016-06-11 12:00
duplicate of #753

**Closed by TanninOne** 2016-06-11 12:00 UTC
