### ISSUE TITLE
[MO2 v2.0.5b] Crash on Close for FO4Edit 3.1.3 AND Fallout4.exe does not close on game exit

### ISSUE THREAD

**Issue by wcarroll4** [TanninOne/modorganizer#741] opened 2016-05-22 04:59 UTC
Interesting pair of (likely related) issues. I just downloaded Beta 1. All applications run fine, but when I go to close FO4Edit 3.1.3 for any reason, I receive the attached error box indicating that xEdit has stopped working. Three screenshots of the error message are attached. The error does not appear to have any effect on FO4Edit's function, however, as it still creates a working Merged Patch, though like a previous error, the capital letters are removed from the file name.

Additionally, when I run Fallout 4 through f4se_loader.exe, the game runs fine and all mods load. However, when I close the game, Mod Organizer stays in the "MO is locked while the executable is running." screen. Using Task Manager, Fallout4.exe continues to run under the Processes tab, through it has been removed from the Applications tab. When loading the game without Mod Organizer, it shuts down normally.

Note that, the first time I installed Mod Organizer Beta 1 and attempted to run f4se_loader.exe, Mod Organizer crashed to desktop. It generated a ModOrganizer.exe.dmp file, which I have emailed with the issue name as the subject line to sherb@gmx.net per the pop-up's instructions.

![fo4edit 3 1 3 0 error pt 1 5 21 16](https://cloud.githubusercontent.com/assets/19512679/15452301/87e9ada2-1faf-11e6-9f7c-4ec7d72791d2.png)
![fo4edit 3 1 3 0 error pt 2 5 21 16](https://cloud.githubusercontent.com/assets/19512679/15452302/87eb742a-1faf-11e6-9515-0002498ba762.png)
![fo4edit 3 1 3 0 error pt 3 5 21 16](https://cloud.githubusercontent.com/assets/19512679/15452303/87eda81c-1faf-11e6-9e6e-6def11a2e24c.png)

**Comment by wcarroll4** [comment] 2016-05-22 05:10
Also note that I have Fallout 4 (and therefore FO4Edit and Mod Organizer) installed in "C:\Games\Steam\SteamApps\common\Fallout 4", NOT in Program Files (x86), if that makes any difference.

**Comment by neokio** [comment] 2016-05-31 02:51
This crash may be related to the Overwrite folder.
I've found that if I open FO4Edit (latest version) without modifying anything, I can close it without problems.
But if edit an .esp in FO4Edit, and save when quitting, my edited .esp ends up in the Overwrite folder (as it should), but MO v2.0.6 crashes. Sometimes immediately, sometimes after a few other simple actions.

**Comment by TanninOne** [comment] 2016-05-31 06:24
I doubt the two issues are related. The xedit problem is probably caused by some platform incompatibility in my internal data structures.
The vfs is stored as a map, mapping real file locations to the virtual locations.
This map is shared between all processes to save memory and so changes are visible to all processes at the same time.
This crash seems to occur when any 64bit application (including mo) tries to read a change (ie added file) caused by a 32bit app (like xedit)

**Closed** 2016-06-21 06:12 UTC
