### ISSUE TITLE
Not using MO Profile INIs, local saves not working

### ISSUE THREAD

**Issue by lasmay** [TanninOne/modorganizer#782] opened 2016-06-03 08:14 UTC
In 2.0.6 and 2.0.5 I believe Mod Organizer is only using default INIs, which is also causing local savegames feature to be broken. If I edit the settings it edits the default INIs under \My Documents\My Games\Fallout 4. I've tried setting it up as portable and the other way. It shows the profile INIs when I use INI Editor, but doesn't load them.

Thank you for making this, after using MO with Skyrim I can never go back to NMM!

**Comment by darkconsole** [comment] 2016-06-03 10:30
i am also seeing this. everything is dumping and pulling from the standard %USERPROFILE%\Documents\My Games\Fallout4 atm.

**Comment by DukeAl** [comment] 2016-06-03 11:35
Just realized the same here after playing around with the inis for an hour and wondering why there was no change in framerate...

**Comment by TanninOne** [comment] 2016-06-03 15:12
Duplicate of #681 and #689

**Closed** 2016-06-03 15:12 UTC
Labels: duplicate
