### ISSUE TITLE
Unable to save in Creation Kit

### ISSUE THREAD

**Issue by rdunlap** [TanninOne/modorganizer#683] opened 2016-05-09 22:40 UTC
Have tried both Save and Push to PC and just Save. Both worked in Alpha 4, both broken in Beta 1. CK freezes up on attempting to save and becomes unstable and has to be force closed.

Robert

**Comment by rdunlap** [comment] 2016-05-09 22:57
Some tests i have made to try to work around.

1. disabled AV 
2. Unlock MO2 interface after starting CK
3. Elevating MO2 to Admin via Run as Administrator

No results. Creation Kit Still freezes when save or save and push to PC is used.

Robert

**Comment by rdunlap** [comment] 2016-05-09 23:38
Just so Information is complete. I just opened xEdit *(FO4Edit) and made a small change and clicked close which brings up the save dialog. It saved the change with no issue and used the Overrite directory as expected.

Robert

**Comment by rdunlap** [comment] 2016-05-09 23:58
Ok some information that may help.
I moved a plugin to the Game Data folder *(Fallout 4) and ran CK using MO2 Beta, made a small change and clicked save. The Creation Kit this time gives me a message box popup saying. "Failed to create temp file. Plugin Data\RebuiltKingsportLighthouse.esp cannot be saved.". I unlocked the MO interface and looked in the overwrite directory and there is a temp file in it from the CK. So the file created but the CK somehow does not see it or didn't get some event notification it was looking for. It does not proceed to write the new file so I am assuming its process is to write temp file and verify then delete existing file, then change the extension of the temp file to esp. 

There are some assumptions involved here so treat it as such. If i can do any other testing to help get more information do let me know. You guys do GREAT work!

Robert

**Comment by rdunlap** [comment] 2016-05-10 00:25
WORKAROUND:
Based on the tests and results listed above the following will allow us to use MO2B1 with the Creation Kit successfully. I have done this several times to assure no data loss and it is stable in this fashion. 

1. before running CK in MO2 Move *(NOT copy) the esp into the Game Data directory and make sure MO2 see's it as Unmanaged.
2. run the Creation Kit and do your work.
3. Click "File>Save" *(it seems to work with save and push as well but i don't trust it). You will get a message box popup as described above about failure to create a temp file. Click Okay. The Creation Kit will still think the esp is unsaved so Ignore that for now.
4. Go to the ModOrganizer 2 window and Unlock the window. Scroll down to the Overwrite folder and open it. You should see your mod in the Overwrite folder with the extension ".tes" 
5. Once you have verified the file is there you can go back to the CK and close it. When it asks to save the changes say NO or the UI will LOCK UP. 
6. move the file from the Overwrite folder to where it needs to go and change the extension back to esp.

Robert

**Comment by rogerdatsir** [comment] 2016-05-12 20:41
I'm also having this issue. Saving in CK just gets stuck in a "Saving..." state.

I appreciate the workaround rdunlap has posted. But, seems just as much of a hassle as moving the entire mod back out to the Fallout 4 folder and running CK without MO2.

**Comment by rdunlap** [comment] 2016-05-15 16:55
Maybe, but the steps for workaround will  help point Tannin in the direction of the problem hopefully. I have been using the workaround because i refuse to dirty up my install directory. I would use NMM if i wanted to do that.  :)

Robert

**Comment by rdunlap** [comment] 2016-05-27 16:44
This issue remains unchanged in MO2B2.

Robert

**Comment by rdunlap** [comment] 2016-05-28 16:12
Some Thoughts and information on this error. It appears as is CK is saving the esp as a ".tes" file as a first step and then expects to delete the original ".esp" file and as a last step rename the ".tes" file as shown by the screen shots attached. Maybe Bethesda is doing some kind of unusual workflow in this process instead of just writing back to the esp? It appears as if the CK does not see the file that was created in overwrite in the first step of the process and errors out.

When I click save this is the popup in the CK.
![ckerror](https://cloud.githubusercontent.com/assets/16065686/15628358/ffe66f58-24cc-11e6-8119-bdf4ef3663f0.jpg)

This is the overwrite showing the CK did in fact create the ".tes" file. A simple rename of the extension to ".esp" gives me a usable esp file with the changes successfully saved to it.
![ckerror2](https://cloud.githubusercontent.com/assets/16065686/15628365/1a4880d4-24cd-11e6-995d-a3ec187cd003.jpg)

Robert

**Comment by prattner** [comment] 2016-06-11 07:20
There's an even more simple workaround.  The .tes file created in your overwrite folder IS your .esp file.  You'll also get a zero byte .esp file at the same time.  Just delete the zero byte .esp and rename the .tes file to a .esp file, and work directly out of the overwrite folder.  No need to have stuff sitting in the actual game folder as an unmanaged mod.

Having to rename the file is a bug, but it is not a show stopper.  The work around is pretty simple.

Extra datum:  No matter what I do, I must close creation kit through the task manager, even if the window goes away after I order the program closed.  I usually, but not always, also need to unlock Mod organizer after closing creation kit.

**Comment by darkconsole** [comment] 2016-06-13 19:19
no. it is a show stopper because it causes CK to lock up for infinity.

**Comment by joelflake** [comment] 2016-06-16 06:41
On its own, the CK2 isn't so bad (though, it's now unable to close itself without a crash after the update I came home to today.)  I started working on a small mod a couple days ago and it's been interesting.  I can confirm everything others have said here about the inability to save .esp files to the overwrite directory as well as the .tes file issue.

After having experienced all of the phenomenon named here, I can confirm there are some issues which are semi-showstopping.  Outside of MO2, I was able to start a really small mod which I'm almost done testing and preparing to release, so this is by no means something that keeps people from working, but I ran into serious issues where I had to re-do parts of the work due to this problem.  Once my mod was loaded in CK2 within MO2 (as opposed to the blank-slate FO4 environment where I started the mod,) I managed to destroy my work upon saving (but it's mostly my fault because I discarded the .tes file.)  The semi-showstopper in this is that the .esp in FO4's Data directory was zero kilobytes and the CK attempted to write to the .tes file we're all familiar with in the MO2 overwrite directory.  I decided I really didn't want to deal with this sort of thing, so I closed CK2 and MO2.  Then, I deleted the .tes file without realizing the data had been stripped out of the .esp created by CK2.  When I opened CK2 in the intended environment, I couldn't load the .esp and this is what prompted me to investigate what happened to it.

I realize that's been reported by other users, but I thought I'd confirm it just for observation's sake.

So someone could potentially lose work from this.  Yes, MO2 is not in a release-ready state and I understand that (which is why I started with a very small mod) and I'm glad to have been in a position to add information to the bug report.  I'm likely going to be in a position to mod outside of MO2 for quite some time, so for me, this isn't such a big deal.  And as I said, non-release software is non-release software (and we're lucky to have access to it at all,) but the bug is actually a bit severe nonetheless.

I'm quite willing to help test further iterations of the project when they are available.

**Comment by rdunlap** [comment] 2016-06-19 16:55
Fixed in Beta 3

Robert

**Comment by darkconsole** [comment] 2016-06-20 02:50
indeed esp saving seems to be good now

**Closed** 2016-06-20 12:38 UTC

**Comment by darkconsole** [comment] 2016-06-21 09:47
this might not really be fixed. twice tonight now CK has crashed on-save resulting in a 0 byte esp AND 0 byte tes, all data lost. something which has never happened when running CK flat without MO.

**Comment by darkconsole** [comment] 2016-06-21 18:45
when this happens launching the next thing in MO causes it to hang.
![capture](https://cloud.githubusercontent.com/assets/9095897/16242070/53fd7e8c-37b6-11e6-8d47-76a215d5d9ba.PNG)

```
04:40:27.009 <14864:16944> [D] SetCurrentDirectoryW [lpPathName=C:\Games\Fallout 4] [reroute.fileName()=C:\Games\Fallout 4] [res=1]
04:40:27.009 <14864:16944> [D] SetCurrentDirectoryW [lpPathName=C:\Games\Fallout 4] [reroute.fileName()=C:\Games\Fallout 4] [res=1]
04:40:27.009 [I] find node C:\Games\Fallout 4\Backup
04:40:27.010 [I] find node C:\Games\Fallout 4\Backup\dcc-bp-lol.esp.7.bak
04:40:27.012 <14864:16944> [D] CopyFileW [readReroute.fileName()=C:\Games\MO2\overwrite\dcc-bp-lol.esp] [writeReroute.fileName()=Data\..\Backup\dcc-bp-lol.esp.7.bak] [res=1] [::GetLastError()=0]
04:40:27.012 <14864:16944> [D] CreateFileW [lpFileName=C:\Games\Fallout 4\Data\dcc-bp-lol.esp] [reroute.fileName()=C:\Games\MO2\overwrite\dcc-bp-lol.esp] [dwDesiredAccess=80000000] [dwCreationDisposition=3] [dwFlagsAndAttributes=8000000] [res=0000000000004A4C] [::GetLastError()=0]
04:40:27.012 <14864:16944> [D] CreateFileW [lpFileName=C:\Games\Fallout 4\Data\dcc-bp-lol.esp] [reroute.fileName()=C:\Games\MO2\overwrite\dcc-bp-lol.esp] [dwDesiredAccess=40000000] [dwCreationDisposition=2] [dwFlagsAndAttributes=8000000] [res=0000000000004A4C] [::GetLastError()=0]
04:40:27.013 <14864:16944> [D] GetCurrentDirectoryW [lpBuffer=<null>] [res=19]
04:40:27.013 <14864:16944> [D] GetCurrentDirectoryW [lpBuffer=C:\Games\Fallout 4] [res=18]
04:40:27.013 <14864:16944> [D] GetCurrentDirectoryW [lpBuffer=<null>] [res=19]
04:40:27.013 <14864:16944> [D] GetCurrentDirectoryW [lpBuffer=C:\Games\Fallout 4] [res=18]
04:40:27.013 <14864:16944> [D] CreateDirectoryW [lpPathName=C:\Games] [reroute.fileName()=C:\Games] [res=1]
04:40:27.013 <14864:16944> [D] CreateDirectoryW [lpPathName=C:\Games] [reroute.fileName()=C:\Games] [res=1]
04:40:27.013 <14864:16944> [I] add file to vfs: Data\dcc-bp-lol.tes
04:40:27.013 <14864:16944> [C] windows exception c0000005
04:40:27.013 <14864:16944> [D] end hook of process 14864
```

**Comment by joelflake** [comment] 2016-06-22 01:02
I can also confirm some sort of residual problem, though I'm not sure MO2 is to blame for most of it.  I've experienced the above-name issue, but a day or two before Beta 3 came out, the Bethesda launcher downloaded a CK update and it was incredibly crashy for me with or without MO2 involved.  When this latest oddity has happened to me, I have observed it correlated with having been running but idle for some time.  I'll keep better track of if/when this happens to see if I can add something useful to the discussion.

**Comment by PapaGeomSnooby** [comment] 2020-09-25 01:28
Hi all,
I was having this issue today as well, but it wasnt crashing my software.
I had one last idea and it actually worked. It was so simple yet unbelievable. Totally turned my day around.

All i did was copy the file i was modding onto my desktop then renamed it. Then moved it back into my data directory then deleted the old file.
Bingo Bango, it was back to normal. I could add/ delete meshes and save no problem!

Hope this helps solve future issues.
