### ISSUE TITLE
[Beta 2.0.6] Local saves not working.

### ISSUE THREAD

**Issue by junkajunka** [TanninOne/modorganizer#776] opened 2016-06-01 07:01 UTC
When creating a new profile in 2.0.6 beta with local save games selected, no save games appear for that profile but the game still uses the default FO4 save game location.

**Comment by michaelrw10** [comment] 2016-06-01 15:38
I'm pretty sure this is a known issue.. i could be wrong, though.

**Comment by TanninOne** [comment] 2016-06-01 16:17
duplicate of issue #377

**Closed by TanninOne** 2016-06-01 16:17 UTC
