### ISSUE TITLE
wierd folder names and dll's in the mo2 beta 2 installer

### ISSUE THREAD

**Issue by Kelryth** [TanninOne/modorganizer#804] opened 2016-06-13 07:38 UTC
theres 2 folders with names like ﾕ  one folder has the mo2 files in it and the other has dlls like dialer.dll. I just want to know if this is the real mod organizer 2 beta installer and not someones Trojan attempt by someone that hacked Tannin's github account.  here's an image of the weird dll folder  http://i.imgur.com/0V6fnXH.jpg  I viewed the archive with 7zip.   Sorry for being so paranoid. beta 1 has thoes files too.

**Comment by TanninOne** [comment] 2016-06-13 08:42
duplicate of #753

**Closed by TanninOne** 2016-06-13 08:42 UTC

**Comment by Kelryth** [comment] 2016-06-13 10:20
no its not' i'm talking about the weird folder name and dll's within the Mod.Organizer-2.0.6.exe installer itself.

**Comment by TanninOne** [comment] 2016-06-13 11:54
Sorry, read too quickly. But the content of the installer is generated by the nsis installer framework so I'm not sure myself what all this is for. The directory in your screenshot is probably part of the library that allows the installer to download packages during install.

**Comment by Jeoshua** [comment] 2016-06-13 15:17
No, the mystery is not solved. NSIS is not a Chinese program, contains no dialer, and that there isn't even CHINESE!

 

Norton reports this as a dialer, but Norton is schizophrenic and will warn you about any program which the authors have not paid protection money to them... so take that with a grain of salt.

 

That being said, I've seen this before... just recently with a friend. It tore her hard drive apart and she had to totally reinstall Windows.

 

Take a close look at those file names. They're not actually Chinese. That's corrupted text in several languages, Chinese, Japanese, and Korean among them... they're all just really high unicode code points, high enough to be in the CJK block. It's as if somewhere along the line the program started adding ascii characters together to get one big number, and processes that as a unicode character, instead of concatenating these letters as strings. Likely, the author has used "string1 + string2"... and that is WRONG. I don't care how Java does it, this isn't written in Java as far as I know.

**Comment by Kelryth** [comment] 2016-06-13 16:16
thats the result of using an exe (xedit.exe loot.exe, f4se.exe) within MO2 and can be fixed by installing https://github.com/TanninOne/modorganizer/releases/download/v2.0.6b/usvfs.7z   That bug is documented here: https://github.com/TanninOne/modorganizer/issues/753
