### ISSUE TITLE
[2.0.4a] Windows installer does not create an uninstaller entry for programs/features

### ISSUE THREAD

**Issue by SierraKomodo** [TanninOne/modorganizer#609] opened 2016-03-10 06:31 UTC
OS: Windows 10, 64-bit

Program was installed in E:/Games/Mod Organizer. The uninstaller exists in the folder, and functions properly, but when using Programs/Features or Add and Remove Programs in windows 10, Mod Organizer isn't shown in the list to uninstall.

Discovered while attempting to do a clean reinstall for another possible issue.

**Comment by TanninOne** [comment] 2016-03-10 07:23
Duplicate of issue #550

**Closed by TanninOne** 2016-03-10 07:23 UTC
