### ISSUE TITLE
Fallout 4 v1.5.157 issue with Mod Organizer Alpha 4

### ISSUE THREAD

**Issue by ZeroGravity83** [TanninOne/modorganizer#676] opened 2016-05-09 13:22 UTC
Hi I just updated Fallout 4 from v1.4.132 to v1.5.157 and now some of the mods are not working anymore. When I select "Continue" in the main menu, it says "This save relies on content that is no longer present. Some objects may no longer be available. Robot Home Defence.esm, ConcealedArmor.esm, ArmorKeyword.esm, Homemaker.esm, Radiant Clouds and Fogs.esp" though these mods are enabled on Mod Organizer.

Does anyone have the same issue? Should we MO users not update to v1.5.157 until Mod Organizer officially supports it? Also, do you think Alpha 5 will fix this issue, and when do you think it'll be released?

And it seems the 1.5 Update comes with an in-game mod manager. So, if we launch the game via Mod Organizer and download mods from Bethesda's mod portal, will these mods work?

Thanks for reading and sorry for my English.

**Comment by KeltecRFB** [comment] 2016-05-09 14:30
Please review #663

**Comment by TanninOne** [comment] 2016-05-09 19:06
Duplicate of #663

**Closed by TanninOne** 2016-05-09 19:06 UTC
