### ISSUE TITLE
[Beta 2.0.5] Ordinal 341 in ssleay32.dll not found

### ISSUE THREAD

**Issue by 4DaDiamonds** [TanninOne/modorganizer#730] opened 2016-05-18 18:59 UTC
For some reason every time I try to load up mod organiser I get an error message stating that ordinal 341 could not be found in ssleay32.dll and the actual .exe refuses to load any further.
I have tried re-installing MO2, taking the separate Qt5.5.7zip from the downloads and replacing the ones in MO2 but I still get nothing.
I am running Win 7 and the alpha worked fine.

**Comment by Asshat** [comment] 2016-05-20 12:09
I've had this issue as well, tried a few fixes but nothing worked

**Comment by TanninOne** [comment] 2016-05-30 05:53
Does anyone still have this in version 2.0.6?

**Comment by TanninOne** [comment] 2016-05-30 05:55
Actually: duplicate of #679

**Closed by TanninOne** 2016-05-30 05:55 UTC
