### ISSUE TITLE
Loot not Starting using Mod Organizer

### ISSUE THREAD

**Issue by mw2mw3rhett** [TanninOne/modorganizer#846] opened 2016-06-28 01:24 UTC
Whenever I start loot by clicking sort I get an error message that says:
> failed to spawn "Loot.exe": failed to start process (The parameter is incorrect. [87])

I have not had this problem before but after using mod organizer once then restarting it I had this issue and I cant get it to start fallout 4

Is this a problem with loot or mod organizer?

Tell me if you need any more information!
[Most Recent Logs.zip](https://github.com/TanninOne/modorganizer/files/336104/Most.Recent.Logs.zip)

Edit: I am using version 2.0.7 of mod organizer and version 0.9.1 of loot

**Comment by remi-gelinas** [comment] 2016-06-28 21:02
I also have this problem as of today.

**Comment by TanninOne** [comment] 2016-06-29 06:01
Duplicate of issue #803

**Closed** 2016-06-29 06:01 UTC
Labels: duplicate
