### ISSUE TITLE
F4SE hangs on start

### ISSUE THREAD

**Issue by Kitsudragon** [TanninOne/modorganizer#751] opened 2016-05-27 06:26 UTC
Windows 7x64, running latest version of MO2. I've tried running both from MO and after using the shortcut generator. In both cases, trying to start with F4SE causes the command window to appear, with the cursor blinking. Then it hangs. I've gotten Fallout to start just fine with just F4SE, but not also with MO. F4SE, despite hanging, will close after clicking the X button, so I don't have to necessarily disable the program through the task manager. Don't know if that's significant, but it's something I observed.

**Comment by TanninOne** [comment] 2016-05-27 07:58
Are you maybe using AVG? If so that is probably the cause (MO 2.0.6 will be compatible though).

f4se itself doesn't have a window you could close with X. What you're actually closing is a command prompt "hosting" f4se and since only f4se hangs but not the cmd this still works.

**Comment by Kitsudragon** [comment] 2016-05-27 08:06
Weird. And yes, I use AVG. It's never prevented F4SE from running in the past, though.

**Comment by rdunlap** [comment] 2016-05-27 12:12
Its actually blocking the injection process for the virtual file system MO uses. Go into AVG and create exceptions for the exe's and dll's in the MO2 folder and one for the folder itself, then run MO2 as Administrator and you will most likely have no more issues. I have had to do this for each version of the Alpha. AVG's Heuristic engine just goes into panic mode when it sees the changed signature of the executable files.

Robert

**Comment by Kitsudragon** [comment] 2016-05-28 01:37
I just tried as requested, put exceptions in AVG for every .exe and .dll in the MO2 folder, as well as an exception for the folder itself. It still hangs on F4SE, both through the MO program and the shortcut executable.

**Comment by Kitsudragon** [comment] 2016-05-29 06:40
Just rechecked the AVG exceptions list, and confirmed that yes, all the applications and dll's in the MO2 directory are excepted, plus the directory itself. Not sure why running the program or the shortcut in admin mode doesn't work.

On the other hand, AVG *did* just install an update to their core program the other day. Maybe they changed how it handles stuff?

**Comment by Kitsudragon** [comment] 2016-05-30 22:05
Not an issue anymore with 2.0.6

**Closed** 2016-05-31 06:16 UTC
